# Roteiro: Engenheiro de Dados
## FASE 4 — dbt (Data Build Tool)

**O que é dbt:** Você escreve SQL. O dbt transforma em pipeline versionado, testado e documentado automaticamente.

**Por que é importante:** É a ferramenta mais pedida para Engenheiro de Dados hoje no Brasil.

---
**Estrutura do projeto criado:**
```
contoso_dbt/
├── dbt_project.yml          ← configuração do projeto
├── profiles.yml             ← conexão com o banco
├── models/
│   ├── staging/             ← camada 1: limpar dados brutos
│   │   ├── sources.yml      ← declara as tabelas de origem
│   │   ├── stg_vendas.sql
│   │   ├── stg_produtos.sql
│   │   ├── stg_lojas.sql
│   │   └── stg_datas.sql
│   └── marts/               ← camada 2: lógica de negócio
│       ├── schema.yml       ← testes e documentação
│       ├── mart_vendas_mensais.sql
│       ├── mart_vendas_por_categoria.sql
│       └── mart_performance_lojas.sql
```

---
**Índice:**
1. Conceitos fundamentais do dbt
2. Instalação
3. Configuração e primeiro teste de conexão
4. Rodar os modelos
5. Rodar os testes
6. Gerar documentação
7. Comandos essenciais
8. Verificar resultados no banco

---
## 1. Conceitos Fundamentais

### Camadas do projeto dbt

| Camada | Pasta | O que faz | Materialização |
|---|---|---|---|
| **Staging** | `models/staging/` | Limpar e renomear dados brutos | View |
| **Marts** | `models/marts/` | Lógica de negócio e agregações | Table |

### A sintaxe especial do dbt

```sql
-- Referenciar tabela de origem (source)
select * from {{ source('contoso', 'FactSales') }}

-- Referenciar outro model dbt (ref)
select * from {{ ref('stg_vendas') }}
```

`{{ source() }}` e `{{ ref() }}` são Jinja2 — o dbt os substitui pelo nome real da tabela ao rodar.

### Por que usar `ref()` em vez de nome direto?
- dbt rastreia as dependências automaticamente
- Garante que `stg_vendas` roda ANTES de `mart_vendas_mensais`
- Gera o lineage (gráfico de dependências) automaticamente

---
## 2. Instalação

In [6]:
# Instalar dbt com adapter para SQL Server
import subprocess, sys

result = subprocess.run(
    [sys.executable, '-m', 'pip', 'install', 'dbt-sqlserver', '-q'],
    capture_output=True, text=True
)
print(result.stdout or 'Instalado com sucesso')
if result.returncode != 0:
    print('ERRO:', result.stderr)

Instalado com sucesso

In [7]:
# Verificar versão instalada
result = subprocess.run(['dbt', '--version'], capture_output=True, text=True)
print(result.stdout)

Core:
  - installed: 1.11.8
  - latest:    1.11.8 - Up to date!

Plugins:
  - fabric:    1.9.3 - Update available!
  - sqlserver: 1.9.0 - Up to date!

  At least one plugin is out of date with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

---
## 3. Configuração e Teste de Conexão

O projeto já está criado na pasta `contoso_dbt/`.  
Precisamos copiar o `profiles.yml` para onde o dbt espera encontrá-lo.

In [8]:
import os, shutil
from pathlib import Path

# dbt procura profiles.yml em ~/.dbt/ por padrão
dbt_dir     = Path.home() / '.dbt'
dbt_dir.mkdir(exist_ok=True)

origem  = Path('contoso_dbt/profiles.yml')
destino = dbt_dir / 'profiles.yml'

shutil.copy(origem, destino)
print(f'profiles.yml copiado para: {destino}')

profiles.yml copiado para: C:\Users\PDCASE\.dbt\profiles.yml

In [9]:
# Testar conexão com o banco
os.chdir('contoso_dbt')

result = subprocess.run(
    ['dbt', 'debug'],
    capture_output=True, text=True
)
print(result.stdout)
if result.returncode != 0:
    print('ERRO:', result.stderr)

16:46:56  Running with dbt=1.11.8
16:46:56  dbt version: 1.11.8
16:46:56  python version: 3.12.4
16:46:56  python path: c:\Users\PDCASE\anaconda3\python.exe
16:46:56  os info: Windows-11-10.0.22621-SP0
16:46:57  Using profiles dir at c:\Users\PDCASE\Desktop\SQL VSCode\contoso_dbt
16:46:57  Using profiles.yml file at c:\Users\PDCASE\Desktop\SQL VSCode\contoso_dbt\profiles.yml
16:46:57  Using dbt_project.yml file at c:\Users\PDCASE\Desktop\SQL VSCode\contoso_dbt\dbt_project.yml
16:46:57  adapter type: sqlserver
16:46:57  adapter version: 1.9.0
16:46:57  Configuration:
16:46:57    profiles.yml file [OK found and valid]
16:46:57    dbt_project.yml file [OK found and valid]
16:46:57  Required dependencies:
16:46:57   - git [OK found]

16:46:57  Connection:
16:46:57    server: localhost
16:46:57    database: ContosoRetailDW
16:46:57    schema: dbt_dev
16:46:57    UID: sa
16:46:57    client_id: None
16:46:57    authentication: sql
16:46:57    encrypt: True
16:46:57    trust_cert: True
16:46:57    retries: 3
16:46:57    login_timeout: 0
16:46:57    query_timeout: 0
16:46:57    trace_flag: False
16:46:57    port: 1433
16:46:57  Registered adapter: sqlserver=1.9.0
16:46:58    Connection test: [OK connection ok]

16:46:58  All checks passed!

---
## 4. Rodar os Modelos

### O que acontece quando você roda `dbt run`:
1. dbt lê os arquivos `.sql` na ordem correta (staging → marts)
2. Substitui `{{ ref() }}` e `{{ source() }}` pelos nomes reais
3. Executa os SQLs no banco
4. Cria views (staging) e tables (marts) automaticamente

In [10]:
# Rodar TODOS os modelos
result = subprocess.run(
    ['dbt', 'run'],
    capture_output=True, text=True
)
print(result.stdout)
if result.returncode != 0:
    print('ERRO:', result.stderr)

16:47:02  Running with dbt=1.11.8
16:47:03  Registered adapter: sqlserver=1.9.0
16:47:05  Found 9 models, 36 data tests, 8 sources, 540 macros
16:47:05
16:47:05  Concurrency: 1 threads (target='dev')
16:47:05
16:47:05  1 of 9 START sql view model dbt_dev_stg.stg_channel ............................ [RUN]
16:47:05  1 of 9 OK created sql view model dbt_dev_stg.stg_channel ....................... [OK in 0.20s]
16:47:05  2 of 9 START sql view model dbt_dev_stg.stg_datas .............................. [RUN]
16:47:05  2 of 9 OK created sql view model dbt_dev_stg.stg_datas ......................... [OK in 0.11s]
16:47:05  3 of 9 START sql view model dbt_dev_stg.stg_lojas .............................. [RUN]
16:47:05  3 of 9 OK created sql view model dbt_dev_stg.stg_lojas ......................... [OK in 0.09s]
16:47:05  4 of 9 START sql view model dbt_dev_stg.stg_produtos ........................... [RUN]
16:47:05  4 of 9 OK created sql view model dbt_dev_stg.stg_produtos ...................... [OK in 0.10s]
16:47:05  5 of 9 START sql view model dbt_dev_stg.stg_vendas ............................. [RUN]
16:47:05  5 of 9 OK created sql view model dbt_dev_stg.stg_vendas ........................ [OK in 0.09s]
16:47:05  6 of 9 START sql table model dbt_dev_marts.mart_performance_lojas .............. [RUN]
16:47:15  6 of 9 OK created sql table model dbt_dev_marts.mart_performance_lojas ......... [OK in 9.20s]
16:47:15  7 of 9 START sql table model dbt_dev_marts.mart_vendas_mensais ................. [RUN]
16:47:17  7 of 9 OK created sql table model dbt_dev_marts.mart_vendas_mensais ............ [OK in 2.13s]
16:47:17  8 of 9 START sql table model dbt_dev_marts.mart_vendas_por_canal ............... [RUN]
16:47:18  8 of 9 OK created sql table model dbt_dev_marts.mart_vendas_por_canal .......... [OK in 1.24s]
16:47:18  9 of 9 START sql table model dbt_dev_marts.mart_vendas_por_categoria ........... [RUN]
16:47:21  9 of 9 OK created sql table model dbt_dev_marts.mart_vendas_por_categoria ...... [OK in 3.15s]
16:47:21
16:47:21  Finished running 4 table models, 5 view models in 0 hours 0 minutes and 16.53 seconds (16.53s).
16:47:21
16:47:21  Completed successfully
16:47:21
16:47:21  Done. PASS=9 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=9

In [11]:
# Rodar só a camada staging
result = subprocess.run(
    ['dbt', 'run', '--select', 'staging'],
    capture_output=True, text=True
)
print(result.stdout)

16:47:26  Running with dbt=1.11.8
16:47:27  Registered adapter: sqlserver=1.9.0
16:47:28  Found 9 models, 36 data tests, 8 sources, 540 macros
16:47:28
16:47:28  Concurrency: 1 threads (target='dev')
16:47:28
16:47:28  1 of 5 START sql view model dbt_dev_stg.stg_channel ............................ [RUN]
16:47:29  1 of 5 OK created sql view model dbt_dev_stg.stg_channel ....................... [OK in 0.20s]
16:47:29  2 of 5 START sql view model dbt_dev_stg.stg_datas .............................. [RUN]
16:47:29  2 of 5 OK created sql view model dbt_dev_stg.stg_datas ......................... [OK in 0.10s]
16:47:29  3 of 5 START sql view model dbt_dev_stg.stg_lojas .............................. [RUN]
16:47:29  3 of 5 OK created sql view model dbt_dev_stg.stg_lojas ......................... [OK in 0.08s]
16:47:29  4 of 5 START sql view model dbt_dev_stg.stg_produtos ........................... [RUN]
16:47:29  4 of 5 OK created sql view model dbt_dev_stg.stg_produtos ...................... [OK in 0.08s]
16:47:29  5 of 5 START sql view model dbt_dev_stg.stg_vendas ............................. [RUN]
16:47:29  5 of 5 OK created sql view model dbt_dev_stg.stg_vendas ........................ [OK in 0.11s]
16:47:29
16:47:29  Finished running 5 view models in 0 hours 0 minutes and 0.79 seconds (0.79s).
16:47:29
16:47:29  Completed successfully
16:47:29
16:47:29  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=5

In [12]:
# Rodar um modelo específico + tudo que depende dele (+)
result = subprocess.run(
    ['dbt', 'run', '--select', 'stg_vendas+'],
    capture_output=True, text=True
)
print(result.stdout)

16:47:34  Running with dbt=1.11.8
16:47:35  Registered adapter: sqlserver=1.9.0
16:47:36  Found 9 models, 36 data tests, 8 sources, 540 macros
16:47:36
16:47:36  Concurrency: 1 threads (target='dev')
16:47:36
16:47:36  1 of 5 START sql view model dbt_dev_stg.stg_vendas ............................. [RUN]
16:47:36  1 of 5 OK created sql view model dbt_dev_stg.stg_vendas ........................ [OK in 0.24s]
16:47:36  2 of 5 START sql table model dbt_dev_marts.mart_performance_lojas .............. [RUN]
16:47:48  2 of 5 OK created sql table model dbt_dev_marts.mart_performance_lojas ......... [OK in 11.28s]
16:47:48  3 of 5 START sql table model dbt_dev_marts.mart_vendas_mensais ................. [RUN]
16:47:50  3 of 5 OK created sql table model dbt_dev_marts.mart_vendas_mensais ............ [OK in 2.95s]
16:47:50  4 of 5 START sql table model dbt_dev_marts.mart_vendas_por_canal ............... [RUN]
16:47:53  4 of 5 OK created sql table model dbt_dev_marts.mart_vendas_por_canal .......... [OK in 2.18s]
16:47:53  5 of 5 START sql table model dbt_dev_marts.mart_vendas_por_categoria ........... [RUN]
16:47:58  5 of 5 OK created sql table model dbt_dev_marts.mart_vendas_por_categoria ...... [OK in 5.00s]
16:47:58
16:47:58  Finished running 4 table models, 1 view model in 0 hours 0 minutes and 21.86 seconds (21.86s).
16:47:58
16:47:58  Completed successfully
16:47:58
16:47:58  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=5

---
## 5. Rodar os Testes

dbt testa automaticamente as regras definidas nos arquivos `schema.yml`:
- `unique` — coluna sem duplicatas
- `not_null` — coluna sem nulos
- `accepted_values` — coluna só tem valores esperados

In [13]:
# Rodar todos os testes
result = subprocess.run(
    ['dbt', 'test'],
    capture_output=True, text=True
)
print(result.stdout)
if result.returncode != 0:
    print('Testes com falha:', result.stderr)

16:48:02  Running with dbt=1.11.8
16:48:03  Registered adapter: sqlserver=1.9.0
16:48:05  Found 9 models, 36 data tests, 8 sources, 540 macros
16:48:05
16:48:05  Concurrency: 1 threads (target='dev')
16:48:05
16:48:05  1 of 36 START test accepted_values_mart_performance_lojas_segmento__Platinum__Gold__Silver__Bronze  [RUN]
16:48:05  1 of 36 PASS accepted_values_mart_performance_lojas_segmento__Platinum__Gold__Silver__Bronze  [PASS in 0.16s]
16:48:05  2 of 36 START test not_null_mart_performance_lojas_loja_key .................... [RUN]
16:48:05  2 of 36 PASS not_null_mart_performance_lojas_loja_key .......................... [PASS in 0.06s]
16:48:05  3 of 36 START test not_null_mart_performance_lojas_nome_loja ................... [RUN]
16:48:05  3 of 36 PASS not_null_mart_performance_lojas_nome_loja ......................... [PASS in 0.04s]
16:48:05  4 of 36 START test not_null_mart_performance_lojas_segmento .................... [RUN]
16:48:05  4 of 36 PASS not_null_mart_performance_lojas_segmento .......................... [PASS in 0.04s]
16:48:05  5 of 36 START test not_null_mart_vendas_mensais_ano ............................ [RUN]
16:48:05  5 of 36 PASS not_null_mart_vendas_mensais_ano .................................. [PASS in 0.04s]
16:48:05  6 of 36 START test not_null_mart_vendas_mensais_lucro_total .................... [RUN]
16:48:05  6 of 36 PASS not_null_mart_vendas_mensais_lucro_total .......................... [PASS in 0.07s]
16:48:05  7 of 36 START test not_null_mart_vendas_mensais_numero_mes ..................... [RUN]
16:48:05  7 of 36 PASS not_null_mart_vendas_mensais_numero_mes ........................... [PASS in 0.07s]
16:48:05  8 of 36 START test not_null_mart_vendas_mensais_receita_total .................. [RUN]
16:48:05  8 of 36 PASS not_null_mart_vendas_mensais_receita_total ........................ [PASS in 0.04s]
16:48:05  9 of 36 START test not_null_mart_vendas_por_canal_ano .......................... [RUN]
16:48:05  9 of 36 PASS not_null_mart_vendas_por_canal_ano ................................ [PASS in 0.03s]
16:48:05  10 of 36 START test not_null_mart_vendas_por_canal_nome_canal .................. [RUN]
16:48:05  10 of 36 PASS not_null_mart_vendas_por_canal_nome_canal ........................ [PASS in 0.04s]
16:48:05  11 of 36 START test not_null_mart_vendas_por_canal_receita_total ............... [RUN]
16:48:05  11 of 36 PASS not_null_mart_vendas_por_canal_receita_total ..................... [PASS in 0.04s]
16:48:05  12 of 36 START test not_null_mart_vendas_por_categoria_ano ..................... [RUN]
16:48:05  12 of 36 PASS not_null_mart_vendas_por_categoria_ano ........................... [PASS in 0.04s]
16:48:05  13 of 36 START test not_null_mart_vendas_por_categoria_categoria ............... [RUN]
16:48:05  13 of 36 PASS not_null_mart_vendas_por_categoria_categoria ..................... [PASS in 0.05s]
16:48:05  14 of 36 START test source_not_null_contoso_DimChannel_ChannelKey .............. [RUN]
16:48:05  14 of 36 PASS source_not_null_contoso_DimChannel_ChannelKey .................... [PASS in 0.04s]
16:48:05  15 of 36 START test source_not_null_contoso_DimChannel_ChannelName ............. [RUN]
16:48:05  15 of 36 PASS source_not_null_contoso_DimChannel_ChannelName ................... [PASS in 0.03s]
16:48:05  16 of 36 START test source_not_null_contoso_DimDate_DateKey .................... [RUN]
16:48:06  16 of 36 PASS source_not_null_contoso_DimDate_DateKey .......................... [PASS in 0.04s]
16:48:06  17 of 36 START test source_not_null_contoso_DimGeography_GeographyKey .......... [RUN]
16:48:06  17 of 36 PASS source_not_null_contoso_DimGeography_GeographyKey ................ [PASS in 0.03s]
16:48:06  18 of 36 START test source_not_null_contoso_DimProductCategory_ProductCategoryKey  [RUN]
16:48:06  18 of 36 PASS source_not_null_contoso_DimProductCategory_ProductCategoryKey .... [PASS in 0.03s]
16:48:06  19 of 36 START test source_not_null_contoso_DimProductSubcategory_ProductSubcategoryKey  [RUN]
16:48:06  19 of 36 PASS source_not_null_contoso_DimProductSubcategory_ProductSubcategoryKey  [PASS in 0.05s]
16:48:06  20 of 36 START test source_not_null_contoso_DimProduct_ProductKey .............. [RUN]
16:48:06  20 of 36 PASS source_not_null_contoso_DimProduct_ProductKey .................... [PASS in 0.04s]
16:48:06  21 of 36 START test source_not_null_contoso_DimStore_StoreKey .................. [RUN]
16:48:06  21 of 36 PASS source_not_null_contoso_DimStore_StoreKey ........................ [PASS in 0.04s]
16:48:06  22 of 36 START test source_not_null_contoso_FactSales_DateKey .................. [RUN]
16:48:06  22 of 36 PASS source_not_null_contoso_FactSales_DateKey ........................ [PASS in 0.04s]
16:48:06  23 of 36 START test source_not_null_contoso_FactSales_ProductKey ............... [RUN]
16:48:06  23 of 36 PASS source_not_null_contoso_FactSales_ProductKey ..................... [PASS in 0.04s]
16:48:06  24 of 36 START test source_not_null_contoso_FactSales_SalesAmount .............. [RUN]
16:48:06  24 of 36 PASS source_not_null_contoso_FactSales_SalesAmount .................... [PASS in 0.05s]
16:48:06  25 of 36 START test source_not_null_contoso_FactSales_SalesKey ................. [RUN]
16:48:06  25 of 36 PASS source_not_null_contoso_FactSales_SalesKey ....................... [PASS in 0.05s]
16:48:06  26 of 36 START test source_not_null_contoso_FactSales_SalesQuantity ............ [RUN]
16:48:06  26 of 36 PASS source_not_null_contoso_FactSales_SalesQuantity .................. [PASS in 0.04s]
16:48:06  27 of 36 START test source_not_null_contoso_FactSales_StoreKey ................. [RUN]
16:48:06  27 of 36 PASS source_not_null_contoso_FactSales_StoreKey ....................... [PASS in 0.04s]
16:48:06  28 of 36 START test source_unique_contoso_DimChannel_ChannelKey ................ [RUN]
16:48:06  28 of 36 PASS source_unique_contoso_DimChannel_ChannelKey ...................... [PASS in 0.06s]
16:48:06  29 of 36 START test source_unique_contoso_DimDate_DateKey ...................... [RUN]
16:48:06  29 of 36 PASS source_unique_contoso_DimDate_DateKey ............................ [PASS in 0.05s]
16:48:06  30 of 36 START test source_unique_contoso_DimGeography_GeographyKey ............ [RUN]
16:48:06  30 of 36 PASS source_unique_contoso_DimGeography_GeographyKey .................. [PASS in 0.05s]
16:48:06  31 of 36 START test source_unique_contoso_DimProductCategory_ProductCategoryKey  [RUN]
16:48:06  31 of 36 PASS source_unique_contoso_DimProductCategory_ProductCategoryKey ...... [PASS in 0.04s]
16:48:06  32 of 36 START test source_unique_contoso_DimProductSubcategory_ProductSubcategoryKey  [RUN]
16:48:06  32 of 36 PASS source_unique_contoso_DimProductSubcategory_ProductSubcategoryKey  [PASS in 0.04s]
16:48:06  33 of 36 START test source_unique_contoso_DimProduct_ProductKey ................ [RUN]
16:48:06  33 of 36 PASS source_unique_contoso_DimProduct_ProductKey ...................... [PASS in 0.04s]
16:48:06  34 of 36 START test source_unique_contoso_DimStore_StoreKey .................... [RUN]
16:48:06  34 of 36 PASS source_unique_contoso_DimStore_StoreKey .......................... [PASS in 0.05s]
16:48:06  35 of 36 START test source_unique_contoso_FactSales_SalesKey ................... [RUN]
16:48:06  35 of 36 PASS source_unique_contoso_FactSales_SalesKey ......................... [PASS in 0.05s]
16:48:06  36 of 36 START test unique_mart_performance_lojas_loja_key ..................... [RUN]
16:48:06  36 of 36 PASS unique_mart_performance_lojas_loja_key ........................... [PASS in 0.06s]
16:48:06
16:48:06  Finished running 36 data tests in 0 hours 0 minutes and 1.96 seconds (1.96s).
16:48:07
16:48:07  Completed successfully
16:48:07
16:48:07  Done. PASS=36 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=36

In [14]:
# Rodar só os testes dos marts
result = subprocess.run(
    ['dbt', 'test', '--select', 'marts'],
    capture_output=True, text=True
)
print(result.stdout)

16:48:12  Running with dbt=1.11.8
16:48:14  Registered adapter: sqlserver=1.9.0
16:48:15  Found 9 models, 36 data tests, 8 sources, 540 macros
16:48:15
16:48:15  Concurrency: 1 threads (target='dev')
16:48:15
16:48:15  1 of 14 START test accepted_values_mart_performance_lojas_segmento__Platinum__Gold__Silver__Bronze  [RUN]
16:48:15  1 of 14 PASS accepted_values_mart_performance_lojas_segmento__Platinum__Gold__Silver__Bronze  [PASS in 0.11s]
16:48:15  2 of 14 START test not_null_mart_performance_lojas_loja_key .................... [RUN]
16:48:15  2 of 14 PASS not_null_mart_performance_lojas_loja_key .......................... [PASS in 0.04s]
16:48:15  3 of 14 START test not_null_mart_performance_lojas_nome_loja ................... [RUN]
16:48:15  3 of 14 PASS not_null_mart_performance_lojas_nome_loja ......................... [PASS in 0.06s]
16:48:15  4 of 14 START test not_null_mart_performance_lojas_segmento .................... [RUN]
16:48:15  4 of 14 PASS not_null_mart_performance_lojas_segmento .......................... [PASS in 0.04s]
16:48:15  5 of 14 START test not_null_mart_vendas_mensais_ano ............................ [RUN]
16:48:16  5 of 14 PASS not_null_mart_vendas_mensais_ano .................................. [PASS in 0.04s]
16:48:16  6 of 14 START test not_null_mart_vendas_mensais_lucro_total .................... [RUN]
16:48:16  6 of 14 PASS not_null_mart_vendas_mensais_lucro_total .......................... [PASS in 0.04s]
16:48:16  7 of 14 START test not_null_mart_vendas_mensais_numero_mes ..................... [RUN]
16:48:16  7 of 14 PASS not_null_mart_vendas_mensais_numero_mes ........................... [PASS in 0.04s]
16:48:16  8 of 14 START test not_null_mart_vendas_mensais_receita_total .................. [RUN]
16:48:16  8 of 14 PASS not_null_mart_vendas_mensais_receita_total ........................ [PASS in 0.04s]
16:48:16  9 of 14 START test not_null_mart_vendas_por_canal_ano .......................... [RUN]
16:48:16  9 of 14 PASS not_null_mart_vendas_por_canal_ano ................................ [PASS in 0.03s]
16:48:16  10 of 14 START test not_null_mart_vendas_por_canal_nome_canal .................. [RUN]
16:48:16  10 of 14 PASS not_null_mart_vendas_por_canal_nome_canal ........................ [PASS in 0.04s]
16:48:16  11 of 14 START test not_null_mart_vendas_por_canal_receita_total ............... [RUN]
16:48:16  11 of 14 PASS not_null_mart_vendas_por_canal_receita_total ..................... [PASS in 0.03s]
16:48:16  12 of 14 START test not_null_mart_vendas_por_categoria_ano ..................... [RUN]
16:48:16  12 of 14 PASS not_null_mart_vendas_por_categoria_ano ........................... [PASS in 0.03s]
16:48:16  13 of 14 START test not_null_mart_vendas_por_categoria_categoria ............... [RUN]
16:48:16  13 of 14 PASS not_null_mart_vendas_por_categoria_categoria ..................... [PASS in 0.03s]
16:48:16  14 of 14 START test unique_mart_performance_lojas_loja_key ..................... [RUN]
16:48:16  14 of 14 PASS unique_mart_performance_lojas_loja_key ........................... [PASS in 0.04s]
16:48:16
16:48:16  Finished running 14 data tests in 0 hours 0 minutes and 0.85 seconds (0.85s).
16:48:16
16:48:16  Completed successfully
16:48:16
16:48:16  Done. PASS=14 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=14

---
## 6. Gerar Documentação

dbt gera um site de documentação automaticamente a partir dos seus arquivos `schema.yml`.

In [15]:
# Gerar documentação
result = subprocess.run(
    ['dbt', 'docs', 'generate'],
    capture_output=True, text=True
)
print(result.stdout)

16:48:20  Running with dbt=1.11.8
16:48:21  Registered adapter: sqlserver=1.9.0
16:48:22  Found 9 models, 36 data tests, 8 sources, 540 macros
16:48:22
16:48:22  Concurrency: 1 threads (target='dev')
16:48:22
16:48:23  Building catalog
16:48:23  Catalog written to c:\Users\PDCASE\Desktop\SQL VSCode\contoso_dbt\target\catalog.json

In [ ]:
# Abrir documentação no navegador (roda servidor local na porta 8080)
# Ctrl+C para parar após visualizar
import threading, webbrowser, time

def abrir_docs():
    time.sleep(2)
    webbrowser.open('http://localhost:8080')

threading.Thread(target=abrir_docs).start()

result = subprocess.run(
    ['dbt', 'docs', 'serve', '--port', '8080'],
    capture_output=True, text=True
)
# Nota: esta célula fica rodando até você parar o servidor (Kernel > Interrupt)

---
## 7. Comandos Essenciais do dbt

| Comando | O que faz |
|---|---|
| `dbt debug` | Testa conexão com o banco |
| `dbt run` | Roda todos os modelos |
| `dbt run --select modelo` | Roda um modelo específico |
| `dbt run --select staging` | Roda toda uma pasta |
| `dbt run --select modelo+` | Roda modelo + todos que dependem dele |
| `dbt test` | Roda todos os testes |
| `dbt docs generate` | Gera documentação |
| `dbt docs serve` | Abre documentação no navegador |
| `dbt compile` | Compila SQL sem executar |
| `dbt build` | `run` + `test` juntos (mais comum no dia a dia) |

In [2]:
import subprocess

result = subprocess.run(
    ['dbt', 'build'],
    capture_output=True, text=True
)

print(result.stdout)

# dbt build = run + test em um comando só (o mais usado no dia a dia)
result = subprocess.run(
    ['dbt', 'build'],
    capture_output=True, text=True
)
print(result.stdout)

16:56:18  Running with dbt=1.11.8
16:56:18  Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\PDCASE\Desktop\SQL VSCode\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml


16:56:23  Running with dbt=1.11.8
16:56:23  Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\PDCASE\Desktop\SQL VSCode\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

---
## 8. Verificar Resultados no Banco

In [12]:
import sys
sys.path.insert(0, '..')

from sqlalchemy import create_engine, text
import pandas as pd

engine = create_engine(
    "mssql+pyodbc://sa:Admin123!@localhost:1433/ContosoRetailDW"
    "?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes"
)

def query(sql):
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn)

# Ver tabelas e views criadas pelo dbt
query("""
    SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA LIKE 'dbt%'
    ORDER BY TABLE_SCHEMA, TABLE_TYPE, TABLE_NAME
""")

    TABLE_SCHEMA                 TABLE_NAME  TABLE_TYPE
0  dbt_dev_marts     mart_performance_lojas  BASE TABLE
1  dbt_dev_marts        mart_vendas_mensais  BASE TABLE
2  dbt_dev_marts      mart_vendas_por_canal  BASE TABLE
3  dbt_dev_marts  mart_vendas_por_categoria  BASE TABLE
4    dbt_dev_stg                stg_channel        VIEW
5    dbt_dev_stg                  stg_datas        VIEW
6    dbt_dev_stg                  stg_lojas        VIEW
7    dbt_dev_stg               stg_produtos        VIEW
8    dbt_dev_stg                 stg_vendas        VIEW

In [9]:
# Consultar o mart de vendas mensais criado pelo dbt
df = query("""
SELECT TOP 12 *
FROM dbt_dev_marts.mart_vendas_mensais
ORDER BY ano, numero_mes
""")

cols_moeda = [
    'receita_total',
    'custo_total',
    'lucro_total',
    'ticket_medio'
]

for col in cols_moeda:
    df[col] = df[col].map(
        lambda x: f"{x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
    )

df['margem_perc'] = df['margem_perc'].map(lambda x: f"{x:.2f}%")

df.head()

,ano,numero_mes,nome_mes,trimestre,semestre,total_pedidos,total_lojas_ativas,total_itens,receita_total,custo_total,lucro_total,ticket_medio,margem_perc
0,2007,200701,January,20071,20071,111207,301,1164359,"269.835.263,23","117.399.409,62","152.435.853,61","2.426,42",56.49%
1,2007,200702,February,20071,20071,106031,301,1160226,"298.215.968,35","129.867.885,96","168.348.082,39","2.812,54",56.45%
2,2007,200703,March,20071,20071,113570,301,1158003,"300.486.926,90","131.605.476,17","168.881.450,73","2.645,83",56.20%
3,2007,200704,April,20072,20071,139355,301,1540164,"400.160.331,60","173.007.844,69","227.152.486,91","2.871,52",56.76%
4,2007,200705,May,20072,20071,142470,301,1578798,"423.429.127,79","182.311.244,48","241.117.883,31","2.972,06",56.94%

In [11]:
# Consultar performance de lojas
query("""
    SELECT TOP 10 
        nome_loja, 
        tipo_loja, 
        pais, 
        receita_total, 
        margem_perc, 
        segmento, 
        ranking_global
    FROM dbt_dev_marts.mart_performance_lojas
    ORDER BY ranking_global
""")

,nome_loja,tipo_loja,pais,receita_total,margem_perc,segmento,ranking_global
0,Contoso Catalog Store,Catalog,United States,1.078008e+09,56.82,Platinum,1
1,Contoso North America Online Store,Online,United States,9.842494e+08,56.64,Platinum,2
2,Contoso Asia Online Store,Online,China,8.870492e+08,56.40,Platinum,3
3,Contoso Europe Online Store,Online,Germany,8.063005e+08,56.60,Platinum,4
4,Contoso North America Reseller,Reseller,United States,6.281687e+08,56.84,Platinum,5
5,Contoso Asia Reseller,Reseller,China,5.639412e+08,56.50,Platinum,6
6,Contoso Europe Reseller,Reseller,France,5.230879e+08,56.57,Platinum,7
7,Contoso Sydney No.1 Store,Store,Australia,3.792955e+07,56.88,Platinum,8
8,Contoso Tehran No.2 Store,Store,Iran,3.773336e+07,56.81,Platinum,9
9,Contoso Sydney No.2 Store,Store,Australia,3.771912e+07,56.77,Platinum,10

---
## Critério para avançar para a Fase 5 (Cloud + Airflow)

Você está pronto quando conseguir:
- [ ] Rodar `dbt build` sem erros
- [ ] Explicar a diferença entre `source()` e `ref()`
- [ ] Adicionar um novo modelo SQL do zero e rodá-lo
- [ ] Adicionar um teste `not_null` ou `unique` em um campo novo
- [ ] Abrir a documentação e navegar pelo lineage